%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # data: [0.0,   -1,   0.0,    -0.03,
  #        -0.225,  0.0,  -0.974,    -0.05,
  #        0.974,   0.0,    -0.225,    0.0,
  #        0.0,   0.0,    0.0,    1.0]
  data: [0.011338,-0.999795,-0.0167884,-0.0483114,
         -0.224548,0.0138149,-0.974365,-0.00763264,
         0.974397,0.0148172,-0.224346,-0.110108,
         0.0,0.0,0.0,1.0]
  # data: [-0.08716,   -0.9962,   0.0,    -0.05,
  #        0.0,  0.0,  -1.0,    -0.02,
  #        0.9962,   -0.08716,    0.0,    -0.05,
  #        0.0,   0.0,    0.0,    1.0]
  # data: [-0.0809989,-0.996702,0.00487843,-0.0359833,
  #         0.00284332,-0.00512555,-0.999983,0.00553517,
  #         0.99671,-0.0809836,0.00324911,0.219,
  #         0,0,0,1.0]
# Params for Canny Edge Extraction

Canny.gray_threshold: 70
Canny.len_threshold: 700

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
# Voxel.size: 0.5
# Voxel.down_sample_size: 0.02
# Plane.min_points_size: 30
# Plane.normal_theta_min: 45
# Plane.normal_theta_max: 135
# Plane.max_size: 8
# Ransac.dis_threshold: 0.02
# Edge.min_dis_threshold: 0.03
# Edge.max_dis_threshold: 0.06

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 1.0
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 30
Plane.normal_theta_max: 150
Plane.max_size: 5
Ransac.dis_threshold: 0.015
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06

# Params for color point clouds
Color.dense: 1
Color.intensity_threshold: 10
